access_key_manager/access_key_manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('api-auth/', include('rest_framework.urls')),
    path('account/', include('account.urls')),
    path('key/', include('management.urls')),
]

access_key_manager/account/urls.py
from django.urls import path
from .views import *

app_name ='account'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('activate/<str:uidb64>/<str:token>', activate, name='activate'),
    path('login/', signin, name='login'),
    path('logout/', signout, name='logout'),
    path('password_reset/', password_reset, name='reset_page'),
    path('password_reset/done/', resetPageDone, name='reset_page_done'),
    path('reset/<uidb64>/<token>', reset_password_confirm, name='password_reset_confirm'),
]

access_key_manager/management/urls.py
from django.urls import path
from .views import *
from django.urls import reverse_lazy

app_name ='management'

urlpatterns = [
    path('', index, name='index'),
    path('feedback/', ListView.as_view(extra_context={'time': timezone.now()}), name='key_list'),
    path('<str:pk>/generate', generate_key, name='generate_key'),
    path('<str:pk>/update', update_key, name='update_key'),
    path('<str:pk>/revoke', revoke_key, name='revoke_key'),

    path('api/', AccessKeyViewAPI.as_view(), name='access_key_view_api'),

    path('school/', school_dashboard, name='school'),
    path('<int:pk>/list/', School_key_view, name='school_key_view'),
    path('<int:school_id>/request/', key_request, name='key_request')
]

access_key_manager/management/models.py
from django.db import models
from account.models import CustomUser

# Create your models here.
class Key(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    ACTIVE = 'active'
    EXPIRED = 'expired'
    REVOKED = 'revoked'
    status = models.CharField(max_length=10, choices=(
        (ACTIVE, 'Active'),
        (EXPIRED, 'Expired'),
        (REVOKED, 'Revoked'),
    ), default= ACTIVE)
    key = models.CharField(max_length=32)
    date_of_procurement = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField()
    school = models.ForeignKey('School', on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.key
    
    def get_username(self):
        return self.user.username
    

class School(models.Model):
    name= models.CharField(max_length= 255)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'
    


    

    

access_key_manager/management/forms.py
from django import forms
from .models import Key, School
from .key_generator import generate_access_key


class AccessKeyForm(forms.ModelForm):
    class Meta:
        model=Key
        fields=('expiry_date',)

    def generate_access_key(self):
        return generate_access_key

    def save(self, commit=True):
        access_key = super().save(commit=False)
        access_key.expiry_date = self.cleaned_data.get('expiry_date')
        access_key.key = self.generate_access_key()
        if commit:
            access_key.save()
        return access_key 


class SchoolForm(forms.ModelForm):
    name = forms.CharField()
    
    class Meta:
        model=School
        fields=('name',) 



class MailForm(forms.Form):
    email = forms.EmailField(max_length=200, required=True)

access_key_manager/management/views.py
# import from rest_framework library
from rest_framework.views import APIView
from rest_framework.response import Response
from django.http import Http404
from .serializers import *
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView
from .forms import AccessKeyForm, MailForm, SchoolForm
from datetime import datetime
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from django.conf import settings
from .models import *
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from .key_generator import generate_access_key
from account.models import CustomUser
from django.utils import timezone


# Create your views here.
def index(request):
    return render(request, 'management/index.html')


@method_decorator(login_required, name='dispatch')
class ListView(ListView):
    model = Key
    template_name = 'management/key_detail.html'
    ordering = ['date_of_procurement']
    context_object_name = 'list'
    paginate_by = 5


@login_required
def revoke_key(request, pk):
    access_key_by_id = get_object_or_404(Key, id=pk)
    access_key_by_id.status = 'revoked'
    access_key_by_id.save()
    messages.success(request,'Access-key has been revoked successfully')
    return redirect('management:key_list')
    # return render(request, 'management/key_list.html')


@login_required
def generate_key(request, pk):
    form = AccessKeyForm()
    user = request.user
    user_by_id = School.objects.get(id=pk)
    if request.method == 'POST':
        form = AccessKeyForm(request.POST)
        if form.is_valid():
            access_key =form.save(commit=False)
            access_key.key = generate_access_key
            access_key.school = user_by_id
            access_key.user =user
            if access_key.expiry_date and access_key.expiry_date < timezone.now():
                messages.warning(request, 'Expiry date cannot be in the past')
                return redirect('management:generate_key', user_by_id.id)
            else:
                access_key.expiry_date = form.cleaned_data['expiry_date']
                access_key.save()

            email_body = render_to_string('school/purchase_key_mail.html', {
                    'user': user,
                    'schools': user_by_id,
                    'domain': get_current_site(request).domain,
                    'access_key': Key.objects.filter(school= user_by_id).first()
                })
            email_body = strip_tags(email_body)
            email_subject = 'Access Key Granted'
            email = send_mail(email_subject, email_body,from_email=user.email, recipient_list=[settings.EMAIL_HOST_USER])
            # email.send()
            return redirect('management:school_key_view', user_by_id.id)
        else:
            form = AccessKeyForm()
    return render(request, 'management/generate_access_key.html',{'form':form, 'schools': user_by_id})


@login_required
def update_key(request, pk):
    access_key = get_object_or_404(Key, id=pk)
    if request.method == 'POST':
        form = AccessKeyForm(request.POST, instance= access_key)
        if form.is_valid():
            if access_key.expiry_date and access_key.expiry_date < timezone.now():
                messages.warning(request, 'Expiry date cannot be in the past')
                return redirect('management:update_key', access_key.pk)
            else:
                access_key.expiry_date = form.cleaned_data['expiry_date']
            access_key.save()
            messages.success(request,'Access-key has been Updated')
            return redirect('management:key_list')
    else:
        form = AccessKeyForm(instance= access_key)
    return render(request, 'management/api_update_form.html', {'form':form, 'access_key': access_key})


@method_decorator(login_required, name='dispatch')
class AccessKeyViewAPI(APIView):
    def get(self, request):
        form = MailForm(request.GET or None)
        if form.is_valid():
            email = form.cleaned_data['email']
            print(email)
            try:
                user = CustomUser.objects.get(email=email)
                school = School.objects.get(user=user)
                # key = get_object_or_404(Key, school=school)
                key = Key.objects.filter(school=school)
                serializers = ProjectSerializer(key, many=True)
                return Response(serializers.data)
            except ( Key.DoesNotExist, CustomUser.DoesNotExist):
                if user.is_superuser:
                    return HttpResponse('<h2>Access denied for Mircro-Focus Administrator...</h2>')
                else:
                    return Http404
        return render(request, 'management/api_form.html', {'form': form})


#School Dashboard
@login_required
def School_key_view(request, pk):
    user = request.user
    school = get_object_or_404(School, id=pk)
    key = Key.objects.filter(school=school).order_by('date_of_procurement')
    paginator = Paginator(key, 5)
    page_number = request.GET.get('page')
    page_object = paginator.get_page(page_number)
    time = timezone.now()
    return render(request, 'school/dashboard.html', {'school':school, 'user':user, 'page_obj': page_object, 'time':time})


@login_required
def school_dashboard(request):
    form = SchoolForm()
    if request.method == 'POST':
        form = SchoolForm(request.POST)
        if form.is_valid():
            user = request.user
            name = form.cleaned_data['name']
            school = School.objects.create(name=name, user=user)
            school.save()
            return redirect('management:school_key_view', pk=school.pk)
        else:
            form = SchoolForm()
    return render(request,'school/school_view.html', {'form':form})


def key_request(request, school_id):
    # school = School.objects.get(id=school_id)
    school = get_object_or_404(School, id=school_id)
    key = Key.objects.filter(school=school, status=Key.ACTIVE).first()
    if key:
        if key.expiry_date > timezone.now():
            return HttpResponse('You have an active key already.')
        else:
            return redirect('management:generate_key', pk=str(school.id))
    else:
        return redirect('management:generate_key', pk=str(school.id))

access_key_manager/management/templates/school/dashboard.html
<html>
<head>
    <title>Dashboard</title>
</head>
<body>
    <span><a href="{% url 'account:logout' %}">Logout</a></span>
    <h1>Dashboard</h1>
    <span><a href="{% url 'management:key_request' school.pk %}">Request for Acess key</a></span>
        <table>
        <tr>
            <th>User</th>
            <th>School</th>
            <th>Key</th>
            <th>Account Status</th>
            <th>Procurement Date</th>
            <th>Expiry Date</th>
            {% if user.is_superuser %}
              <th>Actions</th>
            {% endif %}
        </tr>
    {% for access_key in page_obj %}
        <tr>
            <td>{{user}}</td>
            <td>{{ access_key.school }}</td>
            <td>{{ access_key.key }}</td>
            <td>
                {% if access_key.expiry_date < time %}
                    Expired
                {% else %}
                    {{ access_key.status }}
                {% endif %}
            </td>
            <td>{{ access_key.date_of_procurement }}</td>
            <td>{{ access_key.expiry_date }}</td>
        </tr>
    {% endfor %}
</table>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

  
</body>
</html>

access_key_manager/management/templates/school/key_request.html
{% extends 'base.html' %}

{% block content %}
{% comment %} {% for school in id%} {% endcomment %}
    <h1>Request for Access Key</h1>
    <p>School: {{ school.name }}</p>
    <p>School ID: {{ school.id }}</p>
    <a href="{% url 'management:school_key_view' school.id %}"> Back To Access Key Page</a>
{% comment %} {% endfor %} {% endcomment %}
{% endblock %}

access_key_manager/management/templates/school/purchase_key_mail.html
<html>

<body>
    <p>Dear, Super Admin</p>
    <p>{{ user.email}} from {{schools.school_name}} has generated an access key, {{access_key.key}}
</body>

access_key_manager/management/templates/school/school_view.html
{% extends 'base.html' %}

{% block content %}
  <h1>Registration of School</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
  <a href="{% url 'account:logout' %}">Logout</a>
{% endblock %}